export const EXAM_TYPE_LABELS: Record<string, string> = {
	HEMOGRAMA_COMPLETO: "Hemograma Completo",
	GLICEMIA_JEJUM: "Glicemia em Jejum",
	HEMOGLOBINA_GLICADA: "Hemoglobina Glicada (HbA1c)",
	COLESTEROL_TOTAL: "Colesterol Total",
	COLESTEROL_HDL: "Colesterol HDL",
	COLESTEROL_LDL: "Colesterol LDL",
	TRIGLICERIDEOS: "Triglicerídeos",
	TSH: "TSH (Tireoide)",
	T4_LIVRE: "T4 Livre",
	T3_LIVRE: "T3 Livre",
	CREATININA: "Creatinina",
	UREIA: "Ureia",
	ACIDO_URICO: "Ácido Úrico",
	TGO: "TGO (AST)",
	TGP: "TGP (ALT)",
	PSA: "PSA (Próstata)",
	VITAMINA_D: "Vitamina D",
	VITAMINA_B12: "Vitamina B12",
	FERRITINA: "Ferritina",
	PCR: "Proteína C Reativa (PCR)",
	VHS: "VHS (Velocidade de Hemossedimentação)",
	URINA_TIPO_I: "Urina Tipo I (EAS)",
	UROCULTURA: "Urocultura",
	COAGULOGRAMA: "Coagulograma",
	SOROLOGIAS_HIV: "Sorologia HIV",
	SOROLOGIAS_HEPATITE_B: "Sorologia Hepatite B",
	SOROLOGIAS_HEPATITE_C: "Sorologia Hepatite C",
	SOROLOGIAS_SIFILIS: "Sorologia Sífilis",
	RAIO_X: "Raio-X",
	ULTRASSONOGRAFIA: "Ultrassonografia",
	ULTRASSOM_ABDOMINAL: "Ultrassom Abdominal",
	ULTRASSOM_PELVICO: "Ultrassom Pélvico",
	TOMOGRAFIA: "Tomografia Computadorizada",
	RESSONANCIA_MAGNETICA: "Ressonância Magnética",
	ECOCARDIOGRAMA: "Ecocardiograma",
	DENSITOMETRIA_OSSEA: "Densitometria Óssea",
	ENDOSCOPIA: "Endoscopia",
	COLONOSCOPIA: "Colonoscopia",
	MAMOGRAFIA: "Mamografia",
	PAPANICOLAU: "Papanicolau",
	PET_CT: "PET-CT",
	ELETROCARDIOGRAMA: "Eletrocardiograma (ECG)",
	TESTE_ERGOMETRICO: "Teste Ergométrico",
	HOLTER_24H: "Holter 24h",
	MAPA: "MAPA (Monitorização Ambulatorial)",
	ELETROENCEFALOGRAMA: "Eletroencefalograma (EEG)",
	ESPIROMETRIA: "Espirometria",
	AUDIOMETRIA: "Audiometria",
	BIOPSIA: "Biópsia",
	MAPA_PRESSAO_ARTERIAL: "Mapa de Pressão Arterial",
};

export const EXAM_TYPE_OPTIONS = Object.entries(EXAM_TYPE_LABELS).map(
	([value, label]) => ({ value, label }),
);
