export const GenderOptions = [
  { label: "Homem", value: "MALE" },
  { label: "Mulher", value: "FEMALE" },
  { label: "Outro", value: "OTHER" },
];

export const IdentificationTypes = [
  "Certidão de Nascimento",
  "Carteira de Motorista",
  "Cartão/Apólice de Seguro Médico",
  "Carteira de Identidade Militar",
  "Carteira de Identidade Nacional",
  "Passaporte",
  "Cartão de Residente Estrangeiro (Green Card)",
  "Cartão de Seguridade Social",
  "Carteira de Identidade Estadual",
  "Carteira de Estudante",
  "Carteira de Eleitor",
];

export const StatusIcon: Record<string, string> = {
  CONFIRMED: "/assets/icons/check.svg",
  confirmed: "/assets/icons/check.svg",
  PENDING: "/assets/icons/pending.svg",
  pending: "/assets/icons/pending.svg",
  CANCELED: "/assets/icons/cancelled.svg",
  canceled: "/assets/icons/cancelled.svg",
  COMPLETED: "/assets/icons/check.svg",
  completed: "/assets/icons/check.svg",
};

export const specialties = [
  "Cardiologia",
  "Dermatologia",
  "Ginecologia",
  "Pediatria",
  "Ortopedia",
  "Oftalmologia",
  "Neurologia",
  "Psiquiatria",
  "Endocrinologia",
  "Gastroenterologia",
  "Oncologia",
  "Urologia",
  "Reumatologia",
  "Pneumologia",
  "Otorinolaringologia",
  "Fisioterapia",
  "Nutrição",
  "Anestesiologia",
  "Medicina de Família",
  "Medicina do Trabalho",
  "Medicina Esportiva",
  "Radiologia",
  "Patologia",
  "Cirurgia Geral",
  "Cirurgia Plástica",
  "Cirurgia Pediátrica",
  "Cirurgia Cardiovascular",
  "Hematologia",
  "Infectologia",
  "Genética Médica",
  "Cuidados Paliativos",
];

export const plans = [
  {
    title: "Grátis",
    monthlyPrice: 0,
    yearlyPrice: 0,
    description: "Recursos essenciais para começar",
    features: [
      "Agendamento básico de consultas",
      "Até 10 consultas por mês",
      "Notificações por e-mail",
      "Relatórios simples",
      "Suporte básico via e-mail",
    ],
    priceIdMonthly: "",
    priceIdYearly: "",
    actionLabel: "Comece Agora",
  },
  {
    title: "Básico",
    monthlyPrice: 50,
    yearlyPrice: 500,
    description: "Recursos adicionais para clínicas pequenas",
    features: [
      "Agendamento ilimitado de consultas",
      "Notificações por SMS",
      "Relatórios detalhados",
      "Suporte prioritário via e-mail",
    ],
    priceIdMonthly: "",
    priceIdYearly: "",
    actionLabel: "Comece Agora",
  },
  {
    title: "Pro",
    monthlyPrice: 75,
    yearlyPrice: 750,
    description: "Perfeito para clínicas de médio porte",
    features: [
      "Agendamento ilimitado de consultas",
      "Integração com calendários externos",
      "Relatórios avançados e análise",
      "Suporte via chat 24/7",
      "Customização de marca",
    ],
    actionLabel: "Comece Agora",
    priceIdMonthly: "",
    priceIdYearly: "",
    popular: true,
  },
];
