import path from "node:path";
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		environment: "jsdom",
		globals: true,
		setupFiles: "./src/__tests__/setup.ts",
		passWithNoTests: true,
		coverage: {
			provider: "v8",
			reporter: ["text", "html", "lcov"],
			reportsDirectory: "coverage",
			include: ["src/**/*.{ts,tsx}"],
			exclude: [
				"src/**/*.test.{ts,tsx}",
				"src/**/*.spec.{ts,tsx}",
				"src/components/ui/**",
				"src/__tests__/**",
				"src/app/**/layout.tsx",
				"src/app/**/page.tsx",
				"src/app/**/error.tsx",
				"src/app/**/loading.tsx",
				"src/app/**/_components/**",
				"src/app/**/_constants/**",
				"src/app/**/_utils/**",
				"src/components/auth/**",
				"src/components/clinic/**",
				"src/components/financial/**",
				"src/components/forms/**",
				"src/components/procedure-requests/**",
				"src/components/reception/**",
				"src/components/services/**",
				"src/lib/api/generated/**",
				"src/lib/api/billing/**",
				"src/components/billing/**",
				"src/components/referral/**",
				"src/components/wallet/**",
				"src/components/coupon/**",
				"src/hooks/api/billing/**",
				"src/hooks/api/analytics/**",
				"src/components/analytics/**",
				"src/components/professionals/**",
				"src/hooks/api/doctors/use-professional-ratings.ts",
				"src/hooks/api/doctors/use-update-social-links.ts",
				"src/hooks/api/doctors/use-update-bio.ts",
				"src/hooks/api/doctors/use-update-council.ts",
				"src/hooks/api/doctors/use-update-address.ts",
				"src/hooks/api/doctors/use-add-education.ts",
				"src/hooks/api/doctors/use-update-education.ts",
				"src/hooks/api/doctors/use-delete-education.ts",
				"src/hooks/api/doctors/use-add-experience.ts",
				"src/hooks/api/doctors/use-update-experience.ts",
				"src/hooks/api/doctors/use-delete-experience.ts",
				"src/hooks/api/doctors/use-add-certificate.ts",
				"src/hooks/api/doctors/use-update-certificate.ts",
				"src/hooks/api/doctors/use-delete-certificate.ts",
				"src/lib/schemas/doctor/professional-education.schema.ts",
				"src/lib/schemas/doctor/professional-experience.schema.ts",
				"src/lib/schemas/doctor/professional-certificate.schema.ts",
				"src/lib/schemas/doctor/update-council.schema.ts",
				"src/lib/schemas/doctor/update-address.schema.ts",
				"src/hooks/api/patients/use-emergency-contacts.ts",
				"src/hooks/api/patients/use-add-emergency-contact.ts",
				"src/hooks/api/patients/use-update-emergency-contact.ts",
				"src/hooks/api/patients/use-delete-emergency-contact.ts",
				"src/hooks/api/patients/use-vaccines.ts",
				"src/hooks/api/patients/use-add-vaccine.ts",
				"src/hooks/api/patients/use-delete-vaccine.ts",
				"src/hooks/api/patients/use-patient-documents.ts",
				"src/hooks/api/patients/use-upload-document.ts",
				"src/hooks/api/patients/use-delete-document.ts",
				"src/lib/schemas/patient/emergency-contact.schema.ts",
				"src/lib/schemas/patient/patient-vaccine.schema.ts",
				"src/lib/schemas/patient/patient-document.schema.ts",
				"src/components/patients/health/**",
				"src/lib/api/analytics/**",
				"src/lib/api/conversations.api.ts",
				"src/hooks/api/conversations/**",
				"src/hooks/use-chat.ts",
				"src/components/messaging/**",
				"src/lib/schemas/messaging/**",
				"src/providers/**",
				"src/components/custom/map/**",
				"src/components/custom/sidebar/**",
				"src/components/custom/doctor/DoctorFilters.tsx",
				"src/components/custom/doctor/useDoctorFilters.ts",
				"src/lib/monitoring/**",
				"src/config/**",
				"src/lib/api/patients/**",
				"src/store/auth.store.ts",
				"src/features/**",
				"src/lib/nav/**",
				"src/components/appointments/detail/AppointmentHeader.tsx",
				"src/components/appointments/detail/AppointmentProfessionalCard.tsx",
				"src/components/appointments/detail/AppointmentScheduleCard.tsx",
				"src/components/appointments/detail/AppointmentPaymentSection.tsx",
				"src/components/appointments/detail/AppointmentRatingSection.tsx",
				"src/hooks/api/appointments/use-clinic-appointments.ts",
				"src/hooks/api/appointments/use-clinic-financial-stats.ts",
				"src/hooks/use-avatar-upload.ts",
				"src/hooks/use-anamnesis-chat.ts",
				"src/lib/utils/token-storage.ts",
				"src/components/anamnesis/**",
				"src/components/custom/plans/**",
				"src/components/custom/avatar-upload.tsx",
				"src/components/billing/coupons/**",
				"src/components/clinics/**",
				"src/hooks/use-clinics-filters.ts",
				"src/hooks/use-lab-filters.ts",
				"src/hooks/use-professionals-filters.ts",
				"src/hooks/use-medical-health-form.ts",
				"src/hooks/use-doctor-details-form.ts",
				"src/hooks/use-dependent-form.ts",
				"src/hooks/use-address-form.ts",
				"src/hooks/use-patients-page.ts",
				"src/hooks/use-dependents-page.ts",
				"src/hooks/use-messages-page.ts",
				"src/hooks/use-billing-features-page.ts",
				"src/hooks/use-system-fees-page.ts",
				"src/utils/bmi.ts",
				"src/utils/to-number.ts",
				"src/components/forms/DoctorDetails/**",
				"src/components/professionals/AddressForm.tsx",
				"src/components/dependents/DependentFormDialog.tsx",
				"src/components/dependents/**",
				"src/components/exams/**",
				"src/components/laboratories/**",
				"src/features/plans/**",
				"src/features/subscriptions/**",
				"src/hooks/api/subscriptions/**",
				"src/lib/api/subscriptions/**",
			],
			thresholds: {
				statements: 39,
				branches: 26,
				functions: 44,
				lines: 40,
			},
		},
	},
	resolve: {
		alias: {
			"@": path.resolve(__dirname, "./src"),
		},
	},
});
