export const PatientDefaultValues = {
	name: "",
	email: "",
	phone: "",
	birthDate: new Date(),
	gender: "male" as const,
	address: "",
	occupation: "",
	emergencyContactName: "",
	emergencyContactNumber: "",
	allergies: "",
	currentMedication: "",
	familyMedicalHistory: "",
	pastMedicalHistory: "",
	identificationDocumentType: "Birth Certificate",
	cpf: "",
	identificationDocument: undefined,
	imageProfile: undefined,
	treatmentConsent: false,
	disclosureConsent: false,
	privacyConsent: false,
};
